### PR TITLE
login page ui update, flow error fix when no classification derrived

### PR DESCRIPTION
**Pull request by lashford**
some ui tweaks:
* [X] login screen
* [X] added more space for graph

screen shot 2015-09-16 at 21 15 49

Bug fix
* [X] when no classification can be made return all possible options

### CODE REVIEW

**Comment by janm399** [comment]
Checked out with iPhone 6+; all good; OK to merge?

P.S. @lashford, can you use Hubflow naming convention? (Easiest if you brew ``hubflow``, then ``git hf feature start $NAME, ..., git hf push, ..., git hf feature finish $NAME``.)

**Comment by tmbo** [comment]
:+1:

**Comment by anirvanc** [comment]
:shipit: :+1:

**Comment by lashford** [comment]
Yeah I think it is ready to merge!  Sorry about the hubflow will do next time.

**Pull request merged**
