### PR TITLE
Label autocompletion

### PR DESCRIPTION
**Pull request by samudurand**
Add an autocompletion to the labelling field to make our life easier when recording new data. The completion is based first on exercises name starting with the same characters and then on the exercises name containing this substring.

- [x] ready for merge and review

### CODE REVIEW

**Comment by duchoang** [comment]
:+1:

**Comment by tmbo** [comment]
:+1:

**Comment by janm399** [comment]
D'oh!

**Comment by samudurand** [comment]
A problem ?

**Comment by janm399** [comment]
I just had a small improvement for code formatting and the strange loops, especially the rather odd
``guard ... else { continue }`` in a for loop that mutates an array.

**Comment by samudurand** [comment]
Err... sorry , Swift beginner ^^

**Comment by janm399** [comment]
NP. I'll open another PR.

**Pull request merged**
