### PR TITLE
Implemented first MLP integration

### PR DESCRIPTION
**Pull request by tmbo**

### CODE REVIEW

**Comment by janm399** [comment]
I'll explore, tidy up and merge.

**Comment by tmbo** [comment]
This can't be merged yet. I implemented a new feature in the MLP lib (that allows to classify multiple examples in one pas instead of using an outer loop. this makes it way faster). This will probably be merged in the next couple of days followed by a pod release.

Another option would be to temporarily copy the code in our repo (its only a single class and header file).

**Comment by janm399** [comment]
I updated the Podfile to pull your branch.

**Comment by tmbo** [comment]
Right, that makes more sense.

**Comment by janm399** [comment]
I'll get some rest now, I'll tidy up the iOS app tomorrow. I added a counter to detect duplicates and duplicate calls to ``[trainingCompleted:]``. That might help us track down the bug if it ever comes back. I'll also write some tests for our Scala server.

**Comment by janm399** [comment]
Integrates with https://github.com/muvr/muvr-pebble/issues/4

**Pull request merged**
